Optimize the Armbian image build process

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -133,6 +133,12 @@ runs:
             cd ${{ github.action_path }}
             echo -e "Starting Armbian rebuild..."
 
+            # Set builder custom signature
+            [[ -n "${{ inputs.builder_name }}" ]] && {
+                builder_name="${{ inputs.builder_name }}"
+                builder_name="${builder_name// /-}"
+            }
+
             armbian_file="${{ inputs.armbian_path }}"
             armbian_filename="${armbian_file##*/}"
             armbian_filepath="build/output/images"
@@ -212,13 +218,26 @@ runs:
             [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
             [[ -n "${{ inputs.armbian_fstype }}" ]] && make_command="${make_command} -t ${{ inputs.armbian_fstype }}"
             [[ -n "${{ inputs.armbian_size }}" ]] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
-            [[ -n "${{ inputs.builder_name }}" ]] && make_command="${make_command} -n ${{ inputs.builder_name }}"
+            [[ -n "${builder_name}" ]] && make_command="${make_command} -n ${builder_name}"
             read -r -a make_args <<< "${make_command}"
             sudo ./rebuild "${make_args[@]}"
 
             cd ${{ github.action_path }}/${armbian_filepath}
-            # Compress Armbian image file
-            pigz -qf *.img || gzip -qf *.img
+            # Compress Armbian image file. Guard against an empty glob (no .img produced) and
+            # prefer pigz when present, otherwise fall back to gzip.
+            shopt -s nullglob
+            imgs=( *.img )
+            shopt -u nullglob
+            if [[ "${#imgs[@]}" -eq 0 ]]; then
+                echo "error: No .img file produced in [ ${PWD} ], aborting."
+                echo "PACKAGED_STATUS=failure" >> ${GITHUB_ENV}
+                exit 1
+            fi
+            if command -v pigz >/dev/null 2>&1; then
+                pigz -qf "${imgs[@]}"
+            else
+                gzip -qf "${imgs[@]}"
+            fi
             sync && sleep 3
 
             cd ${{ github.action_path }}
@@ -235,6 +254,12 @@ runs:
 
             cd ${{ github.action_path }}
             echo -e "Starting kernel compilation..."
+
+            # Set kernel custom signature
+            [[ -n "${{ inputs.kernel_sign }}" ]] && {
+                kernel_sign="${{ inputs.kernel_sign }}"
+                kernel_sign="${kernel_sign// /-}"
+            }
 
             # Custom kernel config files
             config_filepath="compile-kernel/tools/config"
@@ -275,7 +300,6 @@ runs:
             [[ -n "${{ inputs.kernel_auto }}" ]] && make_command="${make_command} -a ${{ inputs.kernel_auto }}"
             [[ -n "${{ inputs.kernel_package }}" ]] && make_command="${make_command} -m ${{ inputs.kernel_package }}"
             [[ -n "${{ inputs.auto_patch }}" ]] && make_command="${make_command} -p ${{ inputs.auto_patch }}"
-            [[ -n "${{ inputs.kernel_sign }}" ]] && make_command="${make_command} -n ${{ inputs.kernel_sign }}"
             [[ -n "${{ inputs.kernel_toolchain }}" ]] && make_command="${make_command} -t ${{ inputs.kernel_toolchain }}"
             [[ -n "${{ inputs.compress_format }}" ]] && make_command="${make_command} -z ${{ inputs.compress_format }}"
             [[ -n "${{ inputs.delete_source }}" ]] && make_command="${make_command} -d ${{ inputs.delete_source }}"
@@ -285,6 +309,7 @@ runs:
             [[ -n "${{ inputs.enable_log }}" ]] && make_command="${make_command} -l ${{ inputs.enable_log }}"
             [[ -n "${{ inputs.docker_hostpath }}" ]] && make_command="${make_command} -h ${{ inputs.docker_hostpath }}"
             [[ -n "${{ inputs.docker_image }}" ]] && make_command="${make_command} -i ${{ inputs.docker_image }}"
+            [[ -n "${kernel_sign}" ]] && make_command="${make_command} -n ${kernel_sign}"
             read -r -a make_args <<< "${make_command}"
             sudo ./recompile "${make_args[@]}"
 
